stages:
  data ingestion:
    cmd: python .\src\data_ingestion.py

    deps:
    - src/data_ingestion.py

    outs:
    - ./data/raw

  data preprocess:
    cmd: python .\src\preprocess.py

    deps:
    - src/data_ingestion.py
    - src/preprocess.py

    outs:
    - ./data/interim


  feature engineering:
    cmd: python .\src\feature_engineering.py

    deps:
    - src/data_ingestion.py
    - src/preprocess.py
    - src/feature_engineering.py

    outs:
    - ./data/processed


  model training:
    cmd: python .\src\model_training.py

    deps:
    - src/data_ingestion.py
    - src/preprocess.py
    - src/feature_engineering.py
    - src/model_training.py

    outs:
    - ./models/RandomForest.joblib

  Evaluation:
    cmd: python .\src\Evaluation.py

    deps:
    - src/data_ingestion.py
    - src/preprocess.py
    - src/feature_engineering.py
    - src/model_training.py
    - src/Evaluation.py

    outs:
    - ./report/metrics.json




params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
