stages:
  data ingestion:
    cmd: python .\src\components\data_ingestion.py

    deps:
    - src/components/data_ingestion.py

    outs:
    - ./data/raw

  data preprocess:
    cmd: python .\src\components\preprocess.py

    deps:
    - src/components/data_ingestion.py
    - src/components/preprocess.py

    outs:
    - ./data/interim


  feature engineering:
    cmd: python .\src\components\feature_engineering.py

    deps:
    - src/components/data_ingestion.py
    - src/components/preprocess.py
    - src/components/feature_engineering.py

    outs:
    - ./data/processed


  model training:
    cmd: python .\src\components\model_training.py

    deps:
    - src/components/data_ingestion.py
    - src/components/preprocess.py
    - src/components/feature_engineering.py
    - src/components/model_training.py

    outs:
    - ./models/RandomForest.joblib

  Evaluation:
    cmd: python .\src\components\Evaluation.py

    deps:
    - src/components/data_ingestion.py
    - src/components/preprocess.py
    - src/components/feature_engineering.py
    - src/components/model_training.py
    - src/components/Evaluation.py

    outs:
    - ./report/metrics.json

params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
