data_ingestion:
  test_size: 0.2
  random_state: 22

feature_engineering:
  max_feature: 100

model_trainning:
  num_estimators: 100
  random_state: 22

# evaluation:
#   (add fields here when ready)
